# ============================================
# MEDIUM TIER - ~€48-55/mo
# ============================================
# Best for: Production, small-medium traffic
# Nodes: 5 (3 masters HA, 2 workers)
# HA: Yes (control plane)
# ============================================

tier: medium
cost_estimate: "€48-55/mo"

global:
  project: k8s          # Resource prefix: k8s-network, k8s-bastion, etc.
  domain: example.com
  email: admin@example.com
  environment: production

# ---------------------------------------------
# Infrastructure
# ---------------------------------------------
infrastructure:
  provider: hetzner
  region: hel1
  
  control_plane:
    count: 3  # HA
    type: cx22
    schedulable: false
  
  workers:
    count: 2
    type: cx32

# ---------------------------------------------
# Network
# ---------------------------------------------
network:
  bastion:
    enabled: true
    server_type: cx22
  
  load_balancer:
    enabled: true
    type: lb11
  
  vpn:
    enabled: true

# ---------------------------------------------
# Kubernetes
# ---------------------------------------------
kubernetes:
  version: v1.34.3
  cni: cilium
  ha_control_plane: true

# ---------------------------------------------
# Storage - ENABLED by default
# ---------------------------------------------
storage:
  enabled: true
  mode: distributed
  replicas: 4
  size_per_replica: 50Gi

# ---------------------------------------------
# Secrets - ENABLED by default
# ---------------------------------------------
secrets:
  enabled: true
  vault:
    replicas: 3  # HA
    storage_size: 10Gi

# ---------------------------------------------
# Databases - ENABLED by default
# ---------------------------------------------
databases:
  postgresql:
    enabled: true
    replicas: 2  # Primary + replica
    storage_size: 20Gi

# ---------------------------------------------
# GitLab - ENABLED by default
# ---------------------------------------------
gitlab:
  enabled: true
  webservice_replicas: 2
  sidekiq_replicas: 2
  runner:
    enabled: true
    concurrent_jobs: 10

# ---------------------------------------------
# GitOps - ENABLED by default
# ---------------------------------------------
gitops:
  enabled: true
  ha_enabled: true

# ---------------------------------------------
# Observability - ENABLED by default
# ---------------------------------------------
observability:
  metrics:
    enabled: true
    retention: 30d
    storage_size: 50Gi
  
  logging:
    enabled: true
    retention: 14d
  
  grafana:
    enabled: true

# ---------------------------------------------
# Autoscaling - ENABLED by default
# ---------------------------------------------
autoscaling:
  enabled: true

# ---------------------------------------------
# Backup
# ---------------------------------------------
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention_days: 30